server:
  port: 10010

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss

# 访问 user 服务: http://localhost:10010/order/4
# 访问 order服务: http://localhost:10010/user/3

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          # 路由的目标地址,去注册中心 eureka 寻找服务
          uri: lb://user-service
          # 路径断言，判断路径是否是以/user开头，如果是则符合
          predicates:
            - Path=/user/**
        - id: order-service
          # 路由的目标地址,去注册中心 eureka 寻找服务
          uri: lb://order-service
          # 路径断言，判断路径是否是以/user开头，如果是则符合
          predicates:
            - Path=/order/**
      # 路由过滤器
      default-filters:
        - AddRequestHeader=truth,permission


# 注册到 eureka 服务中心
eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://localhost:10086/eureka