# 为了做服务注册, 的配置信息
server:
  port: 10086 # 服务端口

spring:
  application:
    name: eureka # eureka 的服务名称

#  eureka 本身也是一个微服务, 注册到 eureka 服务中心
eureka:
  client:
    service-url:  # eureka 的地址信息
      defaultZone: http://localhost:10086/eureka
    fetch-registry: true