person:
  boss: true
  birth: 2019/3/9
  age: 23
  #interests: [篮球, 足球, 排球]
  interests:
    - 篮球
    - 足球
    - 排球
    - 跑步
    - 马拉松
  animal: [阿猫, 阿狗, 公鸡]
#  score:
#    english: 80
#    math: 90
  score: {english:80, math:90}
  salarys:
    - 98.98
    - 99.99
    - 39.22
  pet:
    name: 阿猫
    weight: 99.87
  allPets:
    sick:
      - {name: 阿猫, weight: 98}
      - name: 阿狗
        weight: 88.88
      - name: 爱宠
        weight: 77.77
    health:
      - {name: 阿华, weight: 90.21}
      - {name: 阿花, weight: 76.33}
      - {name: 阿吉, weight: 66.66}
  user-name: zhangsan8lisi

#spring:
#  mvc:
#    static-path-pattern: /static/**

